-- 1. Agenci rezerwacji
CREATE TABLE Booking_Agents (
    agent_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_name VARCHAR2(255) NOT NULL,
    agent_details CLOB
);

-- 2. Pasażerowie
CREATE TABLE Passengers (
    passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    second_name VARCHAR2(100),
    last_name VARCHAR2(100) NOT NULL,
    phone_number VARCHAR2(20),
    email_address VARCHAR2(255),
    address_lines VARCHAR2(1000),
    city VARCHAR2(100),
    state_province_county VARCHAR2(100),
    country VARCHAR2(100),
    other_passenger_details CLOB
);

-- 3. Lotniska
CREATE TABLE Airports (
    airport_code CHAR(3) PRIMARY KEY,
    airport_name VARCHAR2(255) NOT NULL,
    airport_location VARCHAR2(255),
    other_details CLOB
);

-- 4. Kalendarz referencyjny
CREATE TABLE Ref_Calendar (
    day_date DATE PRIMARY KEY,
    day_number NUMBER(3),
    business_day_yn CHAR(1) CHECK (business_day_yn IN ('Y', 'N'))
);

-- 5. Harmonogram lotów (Flight Schedules)
CREATE TABLE Flight_Schedules (
    flight_number VARCHAR2(20) PRIMARY KEY,
    airline_code CHAR(3),
    usual_aircraft_type_code VARCHAR2(50),
    origin_airport_code CHAR(3) CONSTRAINT fk_sched_origin REFERENCES Airports(airport_code),
    destination_airport_code CHAR(3) CONSTRAINT fk_sched_dest REFERENCES Airports(airport_code),
    departure_date_time TIMESTAMP WITH TIME ZONE,
    arrival_date_time TIMESTAMP WITH TIME ZONE
);

-- 6. Koszty lotów
CREATE TABLE Flight_Costs (
    flight_number VARCHAR2(20) REFERENCES Flight_Schedules(flight_number),
    aircraft_type_code VARCHAR2(50),
    valid_from_date DATE,
    valid_to_date DATE,
    flight_cost NUMBER(12, 2),
    CONSTRAINT pk_flight_costs PRIMARY KEY (flight_number, valid_from_date)
);

-- 7. Rezerwacje (Itinerary Reservations)
CREATE TABLE Itinerary_Reservations (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id NUMBER REFERENCES Booking_Agents(agent_id),
    passenger_id NUMBER REFERENCES Passengers(passenger_id),
    reservation_status_code VARCHAR2(20),
    ticket_type_code VARCHAR2(20),
    travel_class_code VARCHAR2(20),
    date_reservation_made DATE DEFAULT SYSDATE,
    number_in_party NUMBER DEFAULT 1
);

-- 8. Płatności
CREATE TABLE Payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_status_code VARCHAR2(20),
    payment_date DATE,
    payment_amount NUMBER(12, 2)
);

-- 9. Tabela łącząca: Rezerwacje i Płatności
CREATE TABLE Reservation_Payments (
    reservation_id NUMBER REFERENCES Itinerary_Reservations(reservation_id),
    payment_id NUMBER REFERENCES Payments(payment_id),
    CONSTRAINT pk_res_pay PRIMARY KEY (reservation_id, payment_id)
);

-- 10. Odcinki lotów (Legs)
CREATE TABLE Legs (
    leg_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR2(20) REFERENCES Flight_Schedules(flight_number),
    origin_airport_code CHAR(3) REFERENCES Airports(airport_code),
    destination_airport_code CHAR(3) REFERENCES Airports(airport_code),
    actual_departure_time TIMESTAMP WITH TIME ZONE,
    actual_arrival_time TIMESTAMP WITH TIME ZONE
);

-- 11. Tabela łącząca: Rezerwacje i Odcinki lotów
CREATE TABLE Itinerary_Legs (
    reservation_id NUMBER REFERENCES Itinerary_Reservations(reservation_id),
    leg_id NUMBER REFERENCES Legs(leg_id),
    CONSTRAINT pk_it_legs PRIMARY KEY (reservation_id, leg_id)
);
