import { jsPDF } from "jspdf"

const formatEuro = (amount) => {
  const value = Number(amount)
  if (Number.isNaN(value)) return "TBD"
  return new Intl.NumberFormat("en-GB", { style: "currency", currency: "EUR" }).format(value)
}

const buildPdfText = (ticket) => {
  const passengers = ticket.passengers.map((p, index) => `  ${index + 1}. ${p.firstName} ${p.lastName} — Seat ${p.seatLabel || ticket.seatLabels[index] || "TBD"}`).join("\n")
  const services = ticket.services.length
    ? ticket.services.map((s) => `  • ${s.name} — ${formatEuro(s.price)}`).join("\n")
    : "  None"

  return {
    header: "Boarding Pass",
    label: `Booking ID: ${ticket.reservationId || ticket.id}`,
    items: [
      { title: "Flight", value: `${ticket.airlineName} ${ticket.flightNumber || ""}` },
      { title: "Route", value: `${ticket.originCity} → ${ticket.destinationCity}` },
      { title: "Departure", value: ticket.departureDate },
      { title: "Seats", value: ticket.seatLabels.join(", ") },
      { title: "Total Paid", value: ticket.totalPrice ? formatEuro(ticket.totalPrice) : "TBD" },
      { title: "Booked at", value: new Date(ticket.bookedAt).toLocaleString() },
    ],
    passengers,
    services,
  }
}

const fetchImageAsDataUrl = async (src) => {
  const response = await fetch(src)
  const blob = await response.blob()
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(reader.result)
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

const createQrCodeUrl = (ticket) => {
  const qrData = {
    id: ticket.reservationId || ticket.id,
    flight: `${ticket.airlineName} ${ticket.flightNumber || ""}`,
    route: `${ticket.originCity} → ${ticket.destinationCity}`,
    seats: ticket.seatLabels,
  }
  return `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(JSON.stringify(qrData))}`
}

const downloadTicket = async (ticket) => {
  const fileName = `boarding-pass-${ticket.reservationId || ticket.id}.pdf`
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const pdf = buildPdfText(ticket)
  const qrSrc = createQrCodeUrl(ticket)
  const qrDataUrl = await fetchImageAsDataUrl(qrSrc)

  doc.setFontSize(22)
  doc.setFont("helvetica", "bold")
  doc.text(pdf.header, 40, 60)

  doc.setFontSize(12)
  doc.setTextColor("#4b5563")
  doc.text(pdf.label, 40, 90)

  doc.addImage(qrDataUrl, "PNG", 395, 60, 130, 130)
  doc.setFontSize(9)
  doc.setTextColor("#6b7280")
  doc.text("Scan at the gate", 410, 200)

  let top = 120
  doc.setFont("helvetica", "normal")
  pdf.items.forEach((item) => {
    doc.setFontSize(10)
    doc.setTextColor("#6b7280")
    doc.text(`${item.title}:`, 40, top)
    doc.setFontSize(12)
    doc.setTextColor("#111827")
    doc.text(item.value, 130, top)
    top += 22
  })

  top += 10
  doc.setDrawColor("#d1d5db")
  doc.setLineWidth(0.5)
  doc.line(40, top, 555, top)
  top += 24

  doc.setFontSize(11)
  doc.setTextColor("#111827")
  doc.text("Passengers:", 40, top)
  top += 18
  doc.setFontSize(10)
  doc.setTextColor("#374151")
  doc.text(pdf.passengers, 40, top, { maxWidth: 520 })

  top += 30
  doc.setFontSize(11)
  doc.setTextColor("#111827")
  doc.text("Extras:", 40, top)
  top += 18
  doc.setFontSize(10)
  doc.setTextColor("#374151")
  doc.text(pdf.services, 40, top, { maxWidth: 520 })

  doc.setFontSize(10)
  doc.setTextColor("#6b7280")
  doc.text("Generated by Flights App", 40, 780)

  doc.save(fileName)
}

export default function MyTickets({ tickets = [], user }) {
  if (!user) {
    return (
      <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm dark:border-slate-700 dark:bg-slate-900">
        <p className="text-slate-700 dark:text-slate-200">Please sign in to view your tickets and boarding passes.</p>
      </div>
    )
  }

  if (!tickets.length) {
    return (
      <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm dark:border-slate-700 dark:bg-slate-900">
        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100 mb-3">My Tickets</h2>
        <p className="text-slate-500 dark:text-slate-400">No saved bookings yet. Book a flight to generate your boarding pass.</p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-700 dark:bg-slate-900">
        <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100">My Tickets</h2>
        <p className="text-sm text-slate-500 dark:text-slate-400">All saved bookings and boarding passes for {user.email}</p>
      </div>

      {tickets.map((ticket) => (
        <div key={ticket.id} className="rounded-3xl border border-slate-200 bg-slate-50 p-6 shadow-sm dark:border-slate-700 dark:bg-slate-950">
          <div className="grid gap-4 md:grid-cols-[1fr_minmax(220px,260px)]">
            <div className="space-y-4">
              <div>
                <p className="text-sm uppercase tracking-wide text-blue-700">Boarding pass</p>
                <h3 className="mt-2 text-2xl font-semibold text-slate-900 dark:text-white">{ticket.originCity} → {ticket.destinationCity}</h3>
                <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{ticket.airlineName} {ticket.flightNumber}</p>
              </div>
              <div className="rounded-3xl bg-white p-4 shadow-sm dark:bg-slate-900">
                <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Boarding ID</p>
                <p className="mt-2 text-lg font-semibold text-slate-900 dark:text-white">{ticket.reservationId || ticket.id}</p>
              </div>
            </div>
            <div className="rounded-3xl bg-white p-4 text-center shadow-sm dark:bg-slate-900">
              <img
                src={`https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(JSON.stringify({
                  id: ticket.reservationId || ticket.id,
                  flight: `${ticket.airlineName} ${ticket.flightNumber || ""}`,
                  route: `${ticket.originCity} → ${ticket.destinationCity}`,
                  seats: ticket.seatLabels,
                }))}`}
                alt="Boarding pass QR code"
                className="mx-auto h-40 w-40 rounded-3xl border border-slate-200 bg-slate-100 dark:border-slate-700"
              />
              <p className="mt-3 text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Gate scan code</p>
              <button
                onClick={() => downloadTicket(ticket)}
                className="mt-4 inline-flex w-full items-center justify-center rounded-2xl bg-blue-700 px-4 py-2 text-sm font-semibold text-white hover:bg-blue-800"
              >
                Download ticket
              </button>
            </div>
          </div>

          <div className="mt-6 grid gap-4 md:grid-cols-3">
            <div className="rounded-3xl bg-white p-4 shadow-sm dark:bg-slate-900">
              <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Departure</p>
              <p className="mt-2 text-lg font-semibold text-slate-900 dark:text-white">{ticket.departureDate}</p>
              <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{ticket.originCity}</p>
            </div>
            <div className="rounded-3xl bg-white p-4 shadow-sm dark:bg-slate-900">
              <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Arrival</p>
              <p className="mt-2 text-lg font-semibold text-slate-900 dark:text-white">{ticket.destinationCity}</p>
              <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{ticket.destinationCity}</p>
            </div>
            <div className="rounded-3xl bg-white p-4 shadow-sm dark:bg-slate-900">
              <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Seats</p>
              <p className="mt-2 text-lg font-semibold text-slate-900 dark:text-white">{ticket.seatLabels.join(", ")}</p>
              <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{ticket.passengers.length} passenger{ticket.passengers.length > 1 ? "s" : ""}</p>
            </div>
          </div>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            <div className="rounded-3xl bg-white p-4 shadow-sm dark:bg-slate-900">
              <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Passengers</p>
              <div className="mt-3 space-y-2 text-sm text-slate-700 dark:text-slate-200">
                {ticket.passengers.map((passenger, index) => (
                  <div key={index} className="rounded-2xl bg-slate-100 p-3 dark:bg-slate-950">
                    <p className="font-semibold">{passenger.firstName || "–"} {passenger.lastName || ""}</p>
                    <p className="text-xs text-slate-500 dark:text-slate-400">Seat {passenger.seatLabel || ticket.seatLabels[index]}</p>
                  </div>
                ))}
              </div>
            </div>
            <div className="rounded-3xl bg-white p-4 shadow-sm dark:bg-slate-900">
              <p className="text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400">Extras</p>
              <div className="mt-3 space-y-2 text-sm text-slate-700 dark:text-slate-200">
                {ticket.services.length ? (
                  ticket.services.map((service) => (
                    <div key={service.id} className="flex items-center justify-between rounded-2xl bg-slate-100 p-3 dark:bg-slate-950">
                      <span>{service.name}</span>
                      <span className="font-semibold">{service.price ? formatEuro(service.price) : "–"}</span>
                    </div>
                  ))
                ) : (
                  <p className="text-slate-500 dark:text-slate-400">No extra services selected</p>
                )}
              </div>
            </div>
          </div>

          <div className="mt-6 flex flex-col gap-4 rounded-3xl border border-dashed border-slate-200 bg-white p-4 text-sm text-slate-700 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300">
            <div className="flex items-center justify-between">
              <span>Total paid</span>
              <span className="font-semibold text-slate-900 dark:text-white">{ticket.totalPrice ? formatEuro(ticket.totalPrice) : "TBD"}</span>
            </div>
            <div className="flex items-center justify-between">
              <span>Booked at</span>
              <span>{new Date(ticket.bookedAt).toLocaleString()}</span>
            </div>
          </div>
        </div>
      ))}
    </div>
  )
}
